#include <gui/screen1_screen/Screen1View.hpp>
#include <touchgfx/Color.hpp>
#include <touchgfx/Unicode.hpp>
#include <touchgfx/events/ClickEvent.hpp>

#ifndef SIMULATOR
extern "C"
{
#include "main.h"
}
#endif

static const char* statusText(SpO2UiStatus status, uint8_t sensorError)
{
    if (status == SPO2_UI_SENSOR_ERROR)
    {
        switch (sensorError)
        {
        case 1U: return "I2C BUS ERROR";
        case 2U: return "MAX30102 MISSING";
        case 3U: return "BAD SENSOR ID";
        case 4U: return "SENSOR TIMEOUT";
        case 6U: return "I2C BUS EMPTY";
        case 7U: return "BUS OK, NO 0x57";
        case 8U: return "SDA STUCK LOW";
        case 9U: return "SCL STUCK LOW";
        case 10U: return "CHECKING SENSOR";
        case 11U: return "FIFO NOT RUNNING";
        default: return "SENSOR ERROR";
        }
    }

    switch (status)
    {
    case SPO2_UI_SENSOR_ERROR:    return "SENSOR ERROR";
    case SPO2_UI_PLACE_FINGER:    return "PLACE FINGER";
    case SPO2_UI_MEASURING:       return "MEASURING...";
    case SPO2_UI_INVALID_SIGNAL:  return "WEAK SIGNAL";
    case SPO2_UI_NORMAL:          return "NORMAL";
    case SPO2_UI_LOW_SPO2:        return "LOW SPO2";
    case SPO2_UI_LOW_HEART_RATE:  return "LOW HEART RATE";
    case SPO2_UI_HIGH_HEART_RATE: return "HIGH HEART RATE";
    default:                      return "---";
    }
}

Screen1View::Screen1View()
    : buttonWasPressed(false)
{
}

void Screen1View::setupScreen()
{
    Screen1ViewBase::setupScreen();

    /* Do not rely on auto-size state inherited from generated code. Explicit
       geometry guarantees every text widget has a non-zero drawable area on
       the target, even if the Designer project is regenerated by another
       TouchGFX patch version. */
    textArea1.setPosition(28, 22, 184, 24);
    textSpO2.setPosition(25, 80, 66, 48);
    textBpm.setPosition(166, 80, 54, 48);
    textTime.setPosition(11, 148, 210, 24);
    textDate.setPosition(11, 206, 210, 24);
    textStatus.setPosition(12, 255, 216, 48);

    /* These panels are real TouchGFX widgets. Besides improving readability,
       they provide an unambiguous first-frame diagnostic without relying on
       font rendering. */
    __background.setColor(touchgfx::Color::getColorFromRGB(5, 12, 24));

    topAccent.setPosition(0, 0, 240, 5);
    topAccent.setColor(touchgfx::Color::getColorFromRGB(40, 180, 255));

    spo2Panel.setPosition(10, 68, 105, 74);
    spo2Panel.setColor(touchgfx::Color::getColorFromRGB(8, 52, 42));

    bpmPanel.setPosition(125, 68, 105, 74);
    bpmPanel.setColor(touchgfx::Color::getColorFromRGB(8, 38, 66));

    timePanel.setPosition(10, 145, 220, 50);
    timePanel.setColor(touchgfx::Color::getColorFromRGB(18, 28, 44));

    datePanel.setPosition(10, 202, 220, 42);
    datePanel.setColor(touchgfx::Color::getColorFromRGB(18, 28, 44));

    statusPanel.setPosition(10, 252, 220, 55);
    statusPanel.setColor(touchgfx::Color::getColorFromRGB(46, 34, 10));

    /* Insert after the background and before all generated text widgets. */
    insert(&__background, topAccent);
    insert(&topAccent, spo2Panel);
    insert(&spo2Panel, bpmPanel);
    insert(&bpmPanel, timePanel);
    insert(&timePanel, datePanel);
    insert(&datePanel, statusPanel);

    SpO2UiData initial = {};
    initial.status = SPO2_UI_SENSOR_ERROR;
    initial.sensorError = 10U;
    initial.measurementValid = false;
    initial.rtcOk = false;
    initial.rtcTimeValid = false;
    updateData(initial);

#ifndef SIMULATOR
    buttonWasPressed = (HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_0) == GPIO_PIN_SET);
#endif
}

void Screen1View::tearDownScreen()
{
    Screen1ViewBase::tearDownScreen();
}

void Screen1View::handleTickEvent()
{
#ifndef SIMULATOR
    const bool pressed = (HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_0) == GPIO_PIN_SET);
    if (pressed && !buttonWasPressed)
    {
        application().gotoScreen2ScreenNoTransition();
    }
    buttonWasPressed = pressed;
#endif
}

void Screen1View::handleClickEvent(const touchgfx::ClickEvent& event)
{
    if (event.getType() == touchgfx::ClickEvent::RELEASED)
    {
        application().gotoScreen2ScreenNoTransition();
    }
}

void Screen1View::updateData(const SpO2UiData& data)
{
    if (data.heartRateValid)
    {
        Unicode::snprintf(textBpmBuffer, TEXTBPM_SIZE, "%d", data.heartRateBpm);
    }
    else
    {
        Unicode::fromUTF8(reinterpret_cast<const uint8_t*>("--"),
                          textBpmBuffer, TEXTBPM_SIZE);
    }

    if (data.spo2Valid)
    {
        Unicode::snprintf(textSpO2Buffer, TEXTSPO2_SIZE, "%d", data.spo2Percent);
    }
    else
    {
        Unicode::fromUTF8(reinterpret_cast<const uint8_t*>("--"),
                          textSpO2Buffer, TEXTSPO2_SIZE);
    }

    if (data.status == SPO2_UI_PLACE_FINGER)
    {
        if (data.bufferedSamples == 0U)
        {
            Unicode::fromUTF8(reinterpret_cast<const uint8_t*>("PLACE FINGER"),
                              textStatusBuffer,
                              TEXTSTATUS_SIZE);
        }
        else
        {
            Unicode::snprintf(textStatusBuffer, TEXTSTATUS_SIZE,
                              "PLACE FINGER %u",
                              static_cast<unsigned>(data.bufferedSamples));
        }
    }
    else if (data.status == SPO2_UI_MEASURING)
    {
        const unsigned progress =
            (data.bufferedSamples >= 100U)
                ? 100U
                : static_cast<unsigned>(data.bufferedSamples);
        if (data.spo2Valid)
        {
            Unicode::snprintf(textStatusBuffer, TEXTSTATUS_SIZE,
                              "MEASURING %u%%",
                              progress);
        }
        else
        {
            Unicode::fromUTF8(reinterpret_cast<const uint8_t*>("MEASURING..."),
                              textStatusBuffer,
                              TEXTSTATUS_SIZE);
        }
    }
    else if (data.status == SPO2_UI_INVALID_SIGNAL)
    {
        Unicode::fromUTF8(reinterpret_cast<const uint8_t*>("WEAK SIGNAL"),
                          textStatusBuffer,
                          TEXTSTATUS_SIZE);
    }
    else if (data.status == SPO2_UI_LOW_SPO2)
    {
        Unicode::snprintf(textStatusBuffer, TEXTSTATUS_SIZE,
                          "LOW SPO2 %d%%",
                          static_cast<int>(data.spo2Percent));
    }
    else
    {
        Unicode::fromUTF8(
            reinterpret_cast<const uint8_t*>(statusText(data.status,
                                                        data.sensorError)),
            textStatusBuffer,
            TEXTSTATUS_SIZE);
    }

    if (data.rtcTimeValid)
    {
        Unicode::snprintf(textTimeBuffer, TEXTTIME_SIZE,
                          "%02u:%02u:%02u",
                          static_cast<unsigned>(data.hour),
                          static_cast<unsigned>(data.minute),
                          static_cast<unsigned>(data.second));
        Unicode::snprintf(textDateBuffer, TEXTDATE_SIZE,
                          "%02u/%02u/%04u",
                          static_cast<unsigned>(data.day),
                          static_cast<unsigned>(data.month),
                          static_cast<unsigned>(data.year));
    }
    else
    {
        Unicode::fromUTF8(reinterpret_cast<const uint8_t*>("--:--:--"),
                          textTimeBuffer, TEXTTIME_SIZE);
        Unicode::fromUTF8(reinterpret_cast<const uint8_t*>("--/--/----"),
                          textDateBuffer, TEXTDATE_SIZE);
    }

    if ((data.status == SPO2_UI_SENSOR_ERROR) ||
        (data.status == SPO2_UI_LOW_SPO2) ||
        (data.status == SPO2_UI_LOW_HEART_RATE) ||
        (data.status == SPO2_UI_HIGH_HEART_RATE))
    {
        textStatus.setColor(touchgfx::Color::getColorFromRGB(255, 96, 96));
    }
    else if (data.status == SPO2_UI_NORMAL)
    {
        textStatus.setColor(touchgfx::Color::getColorFromRGB(90, 230, 140));
    }
    else
    {
        textStatus.setColor(touchgfx::Color::getColorFromRGB(255, 210, 80));
    }

    /* Keep a fixed two-line status rectangle. The V15 one-line diagnostic was
       wider than the 240 px LCD, then resizeToCurrentText() centered it with a
       negative X coordinate. That made the I/R values appear to be missing. */
    statusPanel.invalidate();

    textBpm.invalidate();
    textSpO2.invalidate();
    textStatus.invalidate();
    textTime.invalidate();
    textDate.invalidate();
}
